services:
  hevy-sync:
    image: ghcr.io/lucasgirod/hevy_sync:latest
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ:?err}
      - HEVY_API_KEY=${HEVY_API_KEY:?err}
      - GARMIN_USERNAME=${GARMIN_USERNAME:?err}
      - GARMIN_PASSWORD=${GARMIN_PASSWORD:?err}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
    restart: no

volumes:
  config:
